#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run1 "/control/execute run1.mac"
/gui/addButton run run2 "/control/execute run2.mac"
/gui/addButton run mpx_test "/control/execute mpx_test.mac"
#
# Gun menu :
/gui/addMenu gps Gun
/gui/addButton gps "50 MeV"  "/gps/energy 50 MeV"
/gui/addButton gps "1 GeV"   "/gps/energy 1 GeV"
/gui/addButton gps "10 GeV"  "/gps/energy 10 GeV"
/gui/addButton gps "e-"      "/gps/particle e-"
/gui/addButton gps "pi0"     "/gps/particle pi0"
/gui/addButton gps "pi+"     "/gps/particle pi+"
/gui/addButton gps "neutron" "/gps/particle neutron"
/gui/addButton gps "proton"  "/gps/particle proton"
#
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
#/Medipix/event/setPrintModulo 100
#
# User defined icon :
/gui/addIcon "Run beam on" user_icon "/run/beamOn 1" run.png 
